# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # 修改 Ruby 安装步骤
      - name: Install ruby-build
        run: |
          git clone https://github.com/rbenv/ruby-build.git
          cd ruby-build
          sudo ./install.sh
      
      - name: Install Ruby
        run: |
          sudo mkdir -p /opt/hostedtoolcache/Ruby/3.1.4/x64
          sudo ruby-build 3.1.4 /opt/hostedtoolcache/Ruby/3.1.4/x64
          sudo touch /opt/hostedtoolcache/Ruby/3.1.4/x64.complete
          echo "PATH=/opt/hostedtoolcache/Ruby/3.1.4/x64/bin:$PATH" >> $GITHUB_ENV
      
      - name: Install bundler and dependencies
        run: |
          gem install bundler
          bundle install
      
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      
      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
